/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ApprovalStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface AreaIncident {
  'severity' : { 'low' : null } |
    { 'severe' : null } |
    { 'moderate' : null },
  'location' : string,
  'incidentType' : string,
}
export interface InviteCode {
  'created' : Time,
  'code' : string,
  'used' : boolean,
}
export interface Profile {
  'profileBadge' : [] | [
    { 'personal' : null } |
      { 'business' : null } |
      { 'flagged' : null }
  ],
  'name' : string,
  'subscriptionTier' : { 'free' : null } |
    { 'elite' : null } |
    { 'black' : null },
  'trustScore' : bigint,
  'isActive' : boolean,
  'verificationLevel' : { 'verified' : null } |
    { 'none' : null } |
    { 'elite' : null } |
    { 'basic' : null },
}
export interface RSVP {
  'name' : string,
  'inviteCode' : string,
  'timestamp' : Time,
  'attending' : boolean,
}
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export interface SubscriptionRecord {
  'buyer' : Principal,
  'tier' : string,
  'sessionId' : string,
  'timestamp' : bigint,
  'seen' : boolean,
}
export type Time = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserApprovalInfo {
  'status' : ApprovalStatus,
  'principal' : Principal,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface WatchlistEntry {
  'id' : bigint,
  'tag' : { 'avoid' : null } |
    { 'safe' : null } |
    { 'unknown' : null },
  'addedAt' : bigint,
  'notes' : string,
  'targetName' : string,
  'interactionHistory' : Array<[bigint, string]>,
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addWatchlistEntry' : ActorMethod<[WatchlistEntry], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'generateInviteCode' : ActorMethod<[], string>,
  'getAllRSVPs' : ActorMethod<[], Array<RSVP>>,
  'getAllUsers' : ActorMethod<[], Array<Profile>>,
  'getAreaIncidents' : ActorMethod<[], Array<AreaIncident>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [Profile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getInviteCodes' : ActorMethod<[], Array<InviteCode>>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getSubscriptionPurchases' : ActorMethod<[], Array<SubscriptionRecord>>,
  'getUnreadAlertCount' : ActorMethod<[], bigint>,
  'getUserProfile' : ActorMethod<[Principal], [] | [Profile]>,
  'getWatchlist' : ActorMethod<[], Array<WatchlistEntry>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isCallerApproved' : ActorMethod<[], boolean>,
  'isEliteTierSubscriber' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'listApprovals' : ActorMethod<[], Array<UserApprovalInfo>>,
  'markAlertRead' : ActorMethod<[bigint], undefined>,
  'markPurchaseSeen' : ActorMethod<[string], undefined>,
  'recordSubscriptionPurchase' : ActorMethod<[string, string], undefined>,
  'removeWatchlistEntry' : ActorMethod<[bigint], undefined>,
  'requestApproval' : ActorMethod<[], undefined>,
  'saveCallerUserProfile' : ActorMethod<[Profile], undefined>,
  'setApproval' : ActorMethod<[Principal, ApprovalStatus], undefined>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'submitRSVP' : ActorMethod<[string, boolean, string], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateWatchlistTag' : ActorMethod<
    [bigint, { 'avoid' : null } | { 'safe' : null } | { 'unknown' : null }],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];
