/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface InviteCode {
  'created' : Time,
  'code' : string,
  'used' : boolean,
}
export interface Profile {
  'profileBadge' : [] | [
    { 'personal' : null } |
      { 'business' : null } |
      { 'flagged' : null }
  ],
  'name' : string,
  'subscriptionTier' : { 'free' : null } |
    { 'elite' : null } |
    { 'black' : null },
  'trustScore' : bigint,
  'isActive' : boolean,
  'verificationLevel' : { 'verified' : null } |
    { 'none' : null } |
    { 'elite' : null } |
    { 'basic' : null },
}
export interface RSVP {
  'name' : string,
  'inviteCode' : string,
  'timestamp' : Time,
  'attending' : boolean,
}
export type Time = bigint;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface WatchlistEntry {
  'id' : bigint,
  'tag' : { 'avoid' : null } |
    { 'safe' : null } |
    { 'unknown' : null },
  'addedAt' : bigint,
  'notes' : string,
  'targetName' : string,
  'interactionHistory' : Array<[bigint, string]>,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addWatchlistEntry' : ActorMethod<[WatchlistEntry], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'generateInviteCode' : ActorMethod<[], string>,
  'getAllRSVPs' : ActorMethod<[], Array<RSVP>>,
  'getAreaIncidents' : ActorMethod<
    [],
    Array<
      {
        'severity' : { 'low' : null } |
          { 'severe' : null } |
          { 'moderate' : null },
        'location' : string,
        'incidentType' : string,
      }
    >
  >,
  'getCallerUserProfile' : ActorMethod<[], [] | [Profile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getInviteCodes' : ActorMethod<[], Array<InviteCode>>,
  'getProfile' : ActorMethod<[], Profile>,
  'getUnreadAlertCount' : ActorMethod<[], bigint>,
  'getUserProfile' : ActorMethod<[Principal], [] | [Profile]>,
  'getWatchlist' : ActorMethod<[], Array<WatchlistEntry>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isEliteSubscriber' : ActorMethod<[], boolean>,
  'markAlertRead' : ActorMethod<[bigint], undefined>,
  'removeWatchlistEntry' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[Profile], undefined>,
  'submitRSVP' : ActorMethod<[string, boolean, string], undefined>,
  'updateProfile' : ActorMethod<[Profile], undefined>,
  'updateWatchlistTag' : ActorMethod<
    [bigint, { 'avoid' : null } | { 'safe' : null } | { 'unknown' : null }],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];