/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const WatchlistEntry = IDL.Record({
  'id' : IDL.Nat,
  'tag' : IDL.Variant({
    'avoid' : IDL.Null,
    'safe' : IDL.Null,
    'unknown' : IDL.Null,
  }),
  'addedAt' : IDL.Int,
  'notes' : IDL.Text,
  'targetName' : IDL.Text,
  'interactionHistory' : IDL.Vec(IDL.Tuple(IDL.Int, IDL.Text)),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const RSVP = IDL.Record({
  'name' : IDL.Text,
  'inviteCode' : IDL.Text,
  'timestamp' : Time,
  'attending' : IDL.Bool,
});
export const Profile = IDL.Record({
  'profileBadge' : IDL.Opt(
    IDL.Variant({
      'personal' : IDL.Null,
      'business' : IDL.Null,
      'flagged' : IDL.Null,
    })
  ),
  'name' : IDL.Text,
  'subscriptionTier' : IDL.Variant({
    'free' : IDL.Null,
    'elite' : IDL.Null,
    'black' : IDL.Null,
  }),
  'trustScore' : IDL.Nat,
  'isActive' : IDL.Bool,
  'verificationLevel' : IDL.Variant({
    'verified' : IDL.Null,
    'none' : IDL.Null,
    'elite' : IDL.Null,
    'basic' : IDL.Null,
  }),
});
export const InviteCode = IDL.Record({
  'created' : Time,
  'code' : IDL.Text,
  'used' : IDL.Bool,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addWatchlistEntry' : IDL.Func([WatchlistEntry], [IDL.Nat], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'generateInviteCode' : IDL.Func([], [IDL.Text], []),
  'getAllRSVPs' : IDL.Func([], [IDL.Vec(RSVP)], ['query']),
  'getAreaIncidents' : IDL.Func(
      [],
      [
        IDL.Vec(
          IDL.Record({
            'severity' : IDL.Variant({
              'low' : IDL.Null,
              'severe' : IDL.Null,
              'moderate' : IDL.Null,
            }),
            'location' : IDL.Text,
            'incidentType' : IDL.Text,
          })
        ),
      ],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(Profile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getInviteCodes' : IDL.Func([], [IDL.Vec(InviteCode)], ['query']),
  'getProfile' : IDL.Func([], [Profile], ['query']),
  'getUnreadAlertCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getUserProfile' : IDL.Func([IDL.Principal], [IDL.Opt(Profile)], ['query']),
  'getWatchlist' : IDL.Func([], [IDL.Vec(WatchlistEntry)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isEliteSubscriber' : IDL.Func([], [IDL.Bool], ['query']),
  'markAlertRead' : IDL.Func([IDL.Nat], [], []),
  'removeWatchlistEntry' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([Profile], [], []),
  'submitRSVP' : IDL.Func([IDL.Text, IDL.Bool, IDL.Text], [], []),
  'updateProfile' : IDL.Func([Profile], [], []),
  'updateWatchlistTag' : IDL.Func(
      [
        IDL.Nat,
        IDL.Variant({
          'avoid' : IDL.Null,
          'safe' : IDL.Null,
          'unknown' : IDL.Null,
        }),
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const WatchlistEntry = IDL.Record({
    'id' : IDL.Nat,
    'tag' : IDL.Variant({
      'avoid' : IDL.Null,
      'safe' : IDL.Null,
      'unknown' : IDL.Null,
    }),
    'addedAt' : IDL.Int,
    'notes' : IDL.Text,
    'targetName' : IDL.Text,
    'interactionHistory' : IDL.Vec(IDL.Tuple(IDL.Int, IDL.Text)),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const RSVP = IDL.Record({
    'name' : IDL.Text,
    'inviteCode' : IDL.Text,
    'timestamp' : Time,
    'attending' : IDL.Bool,
  });
  const Profile = IDL.Record({
    'profileBadge' : IDL.Opt(
      IDL.Variant({
        'personal' : IDL.Null,
        'business' : IDL.Null,
        'flagged' : IDL.Null,
      })
    ),
    'name' : IDL.Text,
    'subscriptionTier' : IDL.Variant({
      'free' : IDL.Null,
      'elite' : IDL.Null,
      'black' : IDL.Null,
    }),
    'trustScore' : IDL.Nat,
    'isActive' : IDL.Bool,
    'verificationLevel' : IDL.Variant({
      'verified' : IDL.Null,
      'none' : IDL.Null,
      'elite' : IDL.Null,
      'basic' : IDL.Null,
    }),
  });
  const InviteCode = IDL.Record({
    'created' : Time,
    'code' : IDL.Text,
    'used' : IDL.Bool,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addWatchlistEntry' : IDL.Func([WatchlistEntry], [IDL.Nat], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'generateInviteCode' : IDL.Func([], [IDL.Text], []),
    'getAllRSVPs' : IDL.Func([], [IDL.Vec(RSVP)], ['query']),
    'getAreaIncidents' : IDL.Func(
        [],
        [
          IDL.Vec(
            IDL.Record({
              'severity' : IDL.Variant({
                'low' : IDL.Null,
                'severe' : IDL.Null,
                'moderate' : IDL.Null,
              }),
              'location' : IDL.Text,
              'incidentType' : IDL.Text,
            })
          ),
        ],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(Profile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getInviteCodes' : IDL.Func([], [IDL.Vec(InviteCode)], ['query']),
    'getProfile' : IDL.Func([], [Profile], ['query']),
    'getUnreadAlertCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getUserProfile' : IDL.Func([IDL.Principal], [IDL.Opt(Profile)], ['query']),
    'getWatchlist' : IDL.Func([], [IDL.Vec(WatchlistEntry)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isEliteSubscriber' : IDL.Func([], [IDL.Bool], ['query']),
    'markAlertRead' : IDL.Func([IDL.Nat], [], []),
    'removeWatchlistEntry' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([Profile], [], []),
    'submitRSVP' : IDL.Func([IDL.Text, IDL.Bool, IDL.Text], [], []),
    'updateProfile' : IDL.Func([Profile], [], []),
    'updateWatchlistTag' : IDL.Func(
        [
          IDL.Nat,
          IDL.Variant({
            'avoid' : IDL.Null,
            'safe' : IDL.Null,
            'unknown' : IDL.Null,
          }),
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };